"""followers

Revision ID: 03472fe4dbc4
Revises: f04d1ad3a317
Create Date: 2021-09-02 13:04:11.614983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03472fe4dbc4'
down_revision = 'f04d1ad3a317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
